name: Java Build

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, edited, synchronize]

    paths:
      - 'Software/LMSourceCode/ImageProcessing/golfsim_tomee_webapp/**.java'
      - 'Software/LMSourceCode/ImageProcessing/golfsim_tomee_webapp/**.xml'  


jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.9.2

      - name: Branch Name
        id: extract_branch
        run: |
          echo $BRANCH_NAME
        shell: bash

      - name: Maven Build
        run: mvn -B package --file Software/LMSourceCode/ImageProcessing/golfsim_tomee_webapp/pom.xml